### PR TITLE
Read 38 bytes from SSL socket

### PR DESCRIPTION
**Pull request by suzukimilanpaak**
Instead of reading a line from TCP socket,  reading 38bytes from SSL socket. It works as far as in my environment. Please can you check it?

### CODE REVIEW

**Comment by cqr** [comment]
What problem is this trying to solve? Does reading the full line not work in your environment? What can you tell us about your environment?

Also, when submitting a patch, please also update the tests to reflect your changes.

**Comment by suzukimilanpaak** [comment]
I must have confused you, sorry. There was a discussion about an issue that some people was getting different token for each time they run rake task of feedback in another forked project. So, my patch was to fix it.

The following is my environment. (Not sure which one of them can cause this);

$ cat /etc/lsb-release 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=9.10
DISTRIB_CODENAME=karmic
DISTRIB_DESCRIPTION="Ubuntu 9.10"

$ ruby -v

ruby 1.8.7 (2010-06-23 patchlevel 299) [i686-linux]

$ gem -v

1.3.7

Anyway, I will look into your spec files.

**Comment by suzukimilanpaak** [comment]
It seems that this can be a matter of environment as you asked me. If you could provide me your environment that'd be helpful for me too.

**Comment by cqr** [comment]
This has been merged.

**Comment by cqr** [comment]
Hey, thanks so much for your help!

**Comment by suzukimilanpaak** [comment]
Hey, glad to hear from you and hear about my patch has been merged. Thank you too for providing me a handy gem.

**Pull request closed without merging**
